---
- hosts: mgmt
  vars:
    switch1: true
    switch2: false

  tasks:
    - ping:
      when: switch1
    - ping:
      when: switch2

    - name: apache2
      import_tasks: sub-tasks/ubuntu.yaml
      when:
        - ansible_os_family == "Debian" #AND
        - ansible_distribution == "Ubuntu"
    - name: httpd
      import_tasks: sub-tasks/centos.yaml
      when:
        - ansible_os_family == "RedHat"
        - ansible_distribution == "CentOS"
    - debug: