---
- name: startbootstrap-sb-admin web remove
  hosts: mgmt

  tasks:
    - name: apache2 service enabled
      service:
        name: apache2
        state: stopped
    - name: apache2 pakage remove
      apt:
        name: apache2
        state: absent
        autoremove: true
    - name: remove directory
      file:
          path: /var/www
          state: absent